package app.guangda.repository.dao;

import app.guangda.repository.model.GdDept;
import app.guangda.repository.model.GdDeptExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GdDeptMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gd_dept
     *
     * @mbggenerated Sat Jan 09 21:57:21 CST 2016
     */
    int countByExample(GdDeptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gd_dept
     *
     * @mbggenerated Sat Jan 09 21:57:21 CST 2016
     */
    int deleteByExample(GdDeptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gd_dept
     *
     * @mbggenerated Sat Jan 09 21:57:21 CST 2016
     */
    int deleteByPrimaryKey(String pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gd_dept
     *
     * @mbggenerated Sat Jan 09 21:57:21 CST 2016
     */
    int insert(GdDept record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gd_dept
     *
     * @mbggenerated Sat Jan 09 21:57:21 CST 2016
     */
    int insertSelective(GdDept record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gd_dept
     *
     * @mbggenerated Sat Jan 09 21:57:21 CST 2016
     */
    List<GdDept> selectByExample(GdDeptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gd_dept
     *
     * @mbggenerated Sat Jan 09 21:57:21 CST 2016
     */
    GdDept selectByPrimaryKey(String pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gd_dept
     *
     * @mbggenerated Sat Jan 09 21:57:21 CST 2016
     */
    int updateByExampleSelective(@Param("record") GdDept record, @Param("example") GdDeptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gd_dept
     *
     * @mbggenerated Sat Jan 09 21:57:21 CST 2016
     */
    int updateByExample(@Param("record") GdDept record, @Param("example") GdDeptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gd_dept
     *
     * @mbggenerated Sat Jan 09 21:57:21 CST 2016
     */
    int updateByPrimaryKeySelective(GdDept record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gd_dept
     *
     * @mbggenerated Sat Jan 09 21:57:21 CST 2016
     */
    int updateByPrimaryKey(GdDept record);
}