package app.guangda.repository.dao;

import app.guangda.repository.model.GdPtoper;
import app.guangda.repository.model.GdPtoperExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GdPtoperMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gd_ptoper
     *
     * @mbggenerated Sat Jan 09 21:57:21 CST 2016
     */
    int countByExample(GdPtoperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gd_ptoper
     *
     * @mbggenerated Sat Jan 09 21:57:21 CST 2016
     */
    int deleteByExample(GdPtoperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gd_ptoper
     *
     * @mbggenerated Sat Jan 09 21:57:21 CST 2016
     */
    int deleteByPrimaryKey(String pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gd_ptoper
     *
     * @mbggenerated Sat Jan 09 21:57:21 CST 2016
     */
    int insert(GdPtoper record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gd_ptoper
     *
     * @mbggenerated Sat Jan 09 21:57:21 CST 2016
     */
    int insertSelective(GdPtoper record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gd_ptoper
     *
     * @mbggenerated Sat Jan 09 21:57:21 CST 2016
     */
    List<GdPtoper> selectByExample(GdPtoperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gd_ptoper
     *
     * @mbggenerated Sat Jan 09 21:57:21 CST 2016
     */
    GdPtoper selectByPrimaryKey(String pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gd_ptoper
     *
     * @mbggenerated Sat Jan 09 21:57:21 CST 2016
     */
    int updateByExampleSelective(@Param("record") GdPtoper record, @Param("example") GdPtoperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gd_ptoper
     *
     * @mbggenerated Sat Jan 09 21:57:21 CST 2016
     */
    int updateByExample(@Param("record") GdPtoper record, @Param("example") GdPtoperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gd_ptoper
     *
     * @mbggenerated Sat Jan 09 21:57:21 CST 2016
     */
    int updateByPrimaryKeySelective(GdPtoper record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gd_ptoper
     *
     * @mbggenerated Sat Jan 09 21:57:21 CST 2016
     */
    int updateByPrimaryKey(GdPtoper record);
}