package app.guangda.repository.dao;

import app.guangda.repository.model.GdSubscribeLog;
import app.guangda.repository.model.GdSubscribeLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GdSubscribeLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gd_subscribe_log
     *
     * @mbggenerated Sat Jan 09 21:57:21 CST 2016
     */
    int countByExample(GdSubscribeLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gd_subscribe_log
     *
     * @mbggenerated Sat Jan 09 21:57:21 CST 2016
     */
    int deleteByExample(GdSubscribeLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gd_subscribe_log
     *
     * @mbggenerated Sat Jan 09 21:57:21 CST 2016
     */
    int deleteByPrimaryKey(String pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gd_subscribe_log
     *
     * @mbggenerated Sat Jan 09 21:57:21 CST 2016
     */
    int insert(GdSubscribeLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gd_subscribe_log
     *
     * @mbggenerated Sat Jan 09 21:57:21 CST 2016
     */
    int insertSelective(GdSubscribeLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gd_subscribe_log
     *
     * @mbggenerated Sat Jan 09 21:57:21 CST 2016
     */
    List<GdSubscribeLog> selectByExample(GdSubscribeLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gd_subscribe_log
     *
     * @mbggenerated Sat Jan 09 21:57:21 CST 2016
     */
    GdSubscribeLog selectByPrimaryKey(String pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gd_subscribe_log
     *
     * @mbggenerated Sat Jan 09 21:57:21 CST 2016
     */
    int updateByExampleSelective(@Param("record") GdSubscribeLog record, @Param("example") GdSubscribeLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gd_subscribe_log
     *
     * @mbggenerated Sat Jan 09 21:57:21 CST 2016
     */
    int updateByExample(@Param("record") GdSubscribeLog record, @Param("example") GdSubscribeLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gd_subscribe_log
     *
     * @mbggenerated Sat Jan 09 21:57:21 CST 2016
     */
    int updateByPrimaryKeySelective(GdSubscribeLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gd_subscribe_log
     *
     * @mbggenerated Sat Jan 09 21:57:21 CST 2016
     */
    int updateByPrimaryKey(GdSubscribeLog record);
}