package app.guangda.repository.model;

public class GdDept {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gd_dept.pkid
     *
     * @mbggenerated Sat Jan 09 21:57:21 CST 2016
     */
    private String pkid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gd_dept.dept_code
     *
     * @mbggenerated Sat Jan 09 21:57:21 CST 2016
     */
    private String deptCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gd_dept.dept_name
     *
     * @mbggenerated Sat Jan 09 21:57:21 CST 2016
     */
    private String deptName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gd_dept.dept_address
     *
     * @mbggenerated Sat Jan 09 21:57:21 CST 2016
     */
    private String deptAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gd_dept.dept_type
     *
     * @mbggenerated Sat Jan 09 21:57:21 CST 2016
     */
    private String deptType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gd_dept.dept_phone
     *
     * @mbggenerated Sat Jan 09 21:57:21 CST 2016
     */
    private String deptPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gd_dept.dept_qrcode
     *
     * @mbggenerated Sat Jan 09 21:57:21 CST 2016
     */
    private String deptQrcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gd_dept.dept_scene_id
     *
     * @mbggenerated Sat Jan 09 21:57:21 CST 2016
     */
    private String deptSceneId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gd_dept.pkid
     *
     * @return the value of gd_dept.pkid
     *
     * @mbggenerated Sat Jan 09 21:57:21 CST 2016
     */
    public String getPkid() {
        return pkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gd_dept.pkid
     *
     * @param pkid the value for gd_dept.pkid
     *
     * @mbggenerated Sat Jan 09 21:57:21 CST 2016
     */
    public void setPkid(String pkid) {
        this.pkid = pkid == null ? null : pkid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gd_dept.dept_code
     *
     * @return the value of gd_dept.dept_code
     *
     * @mbggenerated Sat Jan 09 21:57:21 CST 2016
     */
    public String getDeptCode() {
        return deptCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gd_dept.dept_code
     *
     * @param deptCode the value for gd_dept.dept_code
     *
     * @mbggenerated Sat Jan 09 21:57:21 CST 2016
     */
    public void setDeptCode(String deptCode) {
        this.deptCode = deptCode == null ? null : deptCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gd_dept.dept_name
     *
     * @return the value of gd_dept.dept_name
     *
     * @mbggenerated Sat Jan 09 21:57:21 CST 2016
     */
    public String getDeptName() {
        return deptName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gd_dept.dept_name
     *
     * @param deptName the value for gd_dept.dept_name
     *
     * @mbggenerated Sat Jan 09 21:57:21 CST 2016
     */
    public void setDeptName(String deptName) {
        this.deptName = deptName == null ? null : deptName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gd_dept.dept_address
     *
     * @return the value of gd_dept.dept_address
     *
     * @mbggenerated Sat Jan 09 21:57:21 CST 2016
     */
    public String getDeptAddress() {
        return deptAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gd_dept.dept_address
     *
     * @param deptAddress the value for gd_dept.dept_address
     *
     * @mbggenerated Sat Jan 09 21:57:21 CST 2016
     */
    public void setDeptAddress(String deptAddress) {
        this.deptAddress = deptAddress == null ? null : deptAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gd_dept.dept_type
     *
     * @return the value of gd_dept.dept_type
     *
     * @mbggenerated Sat Jan 09 21:57:21 CST 2016
     */
    public String getDeptType() {
        return deptType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gd_dept.dept_type
     *
     * @param deptType the value for gd_dept.dept_type
     *
     * @mbggenerated Sat Jan 09 21:57:21 CST 2016
     */
    public void setDeptType(String deptType) {
        this.deptType = deptType == null ? null : deptType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gd_dept.dept_phone
     *
     * @return the value of gd_dept.dept_phone
     *
     * @mbggenerated Sat Jan 09 21:57:21 CST 2016
     */
    public String getDeptPhone() {
        return deptPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gd_dept.dept_phone
     *
     * @param deptPhone the value for gd_dept.dept_phone
     *
     * @mbggenerated Sat Jan 09 21:57:21 CST 2016
     */
    public void setDeptPhone(String deptPhone) {
        this.deptPhone = deptPhone == null ? null : deptPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gd_dept.dept_qrcode
     *
     * @return the value of gd_dept.dept_qrcode
     *
     * @mbggenerated Sat Jan 09 21:57:21 CST 2016
     */
    public String getDeptQrcode() {
        return deptQrcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gd_dept.dept_qrcode
     *
     * @param deptQrcode the value for gd_dept.dept_qrcode
     *
     * @mbggenerated Sat Jan 09 21:57:21 CST 2016
     */
    public void setDeptQrcode(String deptQrcode) {
        this.deptQrcode = deptQrcode == null ? null : deptQrcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gd_dept.dept_scene_id
     *
     * @return the value of gd_dept.dept_scene_id
     *
     * @mbggenerated Sat Jan 09 21:57:21 CST 2016
     */
    public String getDeptSceneId() {
        return deptSceneId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gd_dept.dept_scene_id
     *
     * @param deptSceneId the value for gd_dept.dept_scene_id
     *
     * @mbggenerated Sat Jan 09 21:57:21 CST 2016
     */
    public void setDeptSceneId(String deptSceneId) {
        this.deptSceneId = deptSceneId == null ? null : deptSceneId.trim();
    }
}