package app.guangda.repository.model;

import java.util.ArrayList;
import java.util.List;

public class GdDeptExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table gd_dept
     *
     * @mbggenerated Sat Jan 09 21:57:21 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table gd_dept
     *
     * @mbggenerated Sat Jan 09 21:57:21 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table gd_dept
     *
     * @mbggenerated Sat Jan 09 21:57:21 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gd_dept
     *
     * @mbggenerated Sat Jan 09 21:57:21 CST 2016
     */
    public GdDeptExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gd_dept
     *
     * @mbggenerated Sat Jan 09 21:57:21 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gd_dept
     *
     * @mbggenerated Sat Jan 09 21:57:21 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gd_dept
     *
     * @mbggenerated Sat Jan 09 21:57:21 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gd_dept
     *
     * @mbggenerated Sat Jan 09 21:57:21 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gd_dept
     *
     * @mbggenerated Sat Jan 09 21:57:21 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gd_dept
     *
     * @mbggenerated Sat Jan 09 21:57:21 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gd_dept
     *
     * @mbggenerated Sat Jan 09 21:57:21 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gd_dept
     *
     * @mbggenerated Sat Jan 09 21:57:21 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gd_dept
     *
     * @mbggenerated Sat Jan 09 21:57:21 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gd_dept
     *
     * @mbggenerated Sat Jan 09 21:57:21 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table gd_dept
     *
     * @mbggenerated Sat Jan 09 21:57:21 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andPkidIsNull() {
            addCriterion("pkid is null");
            return (Criteria) this;
        }

        public Criteria andPkidIsNotNull() {
            addCriterion("pkid is not null");
            return (Criteria) this;
        }

        public Criteria andPkidEqualTo(String value) {
            addCriterion("pkid =", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidNotEqualTo(String value) {
            addCriterion("pkid <>", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidGreaterThan(String value) {
            addCriterion("pkid >", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidGreaterThanOrEqualTo(String value) {
            addCriterion("pkid >=", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidLessThan(String value) {
            addCriterion("pkid <", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidLessThanOrEqualTo(String value) {
            addCriterion("pkid <=", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidLike(String value) {
            addCriterion("pkid like", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidNotLike(String value) {
            addCriterion("pkid not like", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidIn(List<String> values) {
            addCriterion("pkid in", values, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidNotIn(List<String> values) {
            addCriterion("pkid not in", values, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidBetween(String value1, String value2) {
            addCriterion("pkid between", value1, value2, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidNotBetween(String value1, String value2) {
            addCriterion("pkid not between", value1, value2, "pkid");
            return (Criteria) this;
        }

        public Criteria andDeptCodeIsNull() {
            addCriterion("dept_code is null");
            return (Criteria) this;
        }

        public Criteria andDeptCodeIsNotNull() {
            addCriterion("dept_code is not null");
            return (Criteria) this;
        }

        public Criteria andDeptCodeEqualTo(String value) {
            addCriterion("dept_code =", value, "deptCode");
            return (Criteria) this;
        }

        public Criteria andDeptCodeNotEqualTo(String value) {
            addCriterion("dept_code <>", value, "deptCode");
            return (Criteria) this;
        }

        public Criteria andDeptCodeGreaterThan(String value) {
            addCriterion("dept_code >", value, "deptCode");
            return (Criteria) this;
        }

        public Criteria andDeptCodeGreaterThanOrEqualTo(String value) {
            addCriterion("dept_code >=", value, "deptCode");
            return (Criteria) this;
        }

        public Criteria andDeptCodeLessThan(String value) {
            addCriterion("dept_code <", value, "deptCode");
            return (Criteria) this;
        }

        public Criteria andDeptCodeLessThanOrEqualTo(String value) {
            addCriterion("dept_code <=", value, "deptCode");
            return (Criteria) this;
        }

        public Criteria andDeptCodeLike(String value) {
            addCriterion("dept_code like", value, "deptCode");
            return (Criteria) this;
        }

        public Criteria andDeptCodeNotLike(String value) {
            addCriterion("dept_code not like", value, "deptCode");
            return (Criteria) this;
        }

        public Criteria andDeptCodeIn(List<String> values) {
            addCriterion("dept_code in", values, "deptCode");
            return (Criteria) this;
        }

        public Criteria andDeptCodeNotIn(List<String> values) {
            addCriterion("dept_code not in", values, "deptCode");
            return (Criteria) this;
        }

        public Criteria andDeptCodeBetween(String value1, String value2) {
            addCriterion("dept_code between", value1, value2, "deptCode");
            return (Criteria) this;
        }

        public Criteria andDeptCodeNotBetween(String value1, String value2) {
            addCriterion("dept_code not between", value1, value2, "deptCode");
            return (Criteria) this;
        }

        public Criteria andDeptNameIsNull() {
            addCriterion("dept_name is null");
            return (Criteria) this;
        }

        public Criteria andDeptNameIsNotNull() {
            addCriterion("dept_name is not null");
            return (Criteria) this;
        }

        public Criteria andDeptNameEqualTo(String value) {
            addCriterion("dept_name =", value, "deptName");
            return (Criteria) this;
        }

        public Criteria andDeptNameNotEqualTo(String value) {
            addCriterion("dept_name <>", value, "deptName");
            return (Criteria) this;
        }

        public Criteria andDeptNameGreaterThan(String value) {
            addCriterion("dept_name >", value, "deptName");
            return (Criteria) this;
        }

        public Criteria andDeptNameGreaterThanOrEqualTo(String value) {
            addCriterion("dept_name >=", value, "deptName");
            return (Criteria) this;
        }

        public Criteria andDeptNameLessThan(String value) {
            addCriterion("dept_name <", value, "deptName");
            return (Criteria) this;
        }

        public Criteria andDeptNameLessThanOrEqualTo(String value) {
            addCriterion("dept_name <=", value, "deptName");
            return (Criteria) this;
        }

        public Criteria andDeptNameLike(String value) {
            addCriterion("dept_name like", value, "deptName");
            return (Criteria) this;
        }

        public Criteria andDeptNameNotLike(String value) {
            addCriterion("dept_name not like", value, "deptName");
            return (Criteria) this;
        }

        public Criteria andDeptNameIn(List<String> values) {
            addCriterion("dept_name in", values, "deptName");
            return (Criteria) this;
        }

        public Criteria andDeptNameNotIn(List<String> values) {
            addCriterion("dept_name not in", values, "deptName");
            return (Criteria) this;
        }

        public Criteria andDeptNameBetween(String value1, String value2) {
            addCriterion("dept_name between", value1, value2, "deptName");
            return (Criteria) this;
        }

        public Criteria andDeptNameNotBetween(String value1, String value2) {
            addCriterion("dept_name not between", value1, value2, "deptName");
            return (Criteria) this;
        }

        public Criteria andDeptAddressIsNull() {
            addCriterion("dept_address is null");
            return (Criteria) this;
        }

        public Criteria andDeptAddressIsNotNull() {
            addCriterion("dept_address is not null");
            return (Criteria) this;
        }

        public Criteria andDeptAddressEqualTo(String value) {
            addCriterion("dept_address =", value, "deptAddress");
            return (Criteria) this;
        }

        public Criteria andDeptAddressNotEqualTo(String value) {
            addCriterion("dept_address <>", value, "deptAddress");
            return (Criteria) this;
        }

        public Criteria andDeptAddressGreaterThan(String value) {
            addCriterion("dept_address >", value, "deptAddress");
            return (Criteria) this;
        }

        public Criteria andDeptAddressGreaterThanOrEqualTo(String value) {
            addCriterion("dept_address >=", value, "deptAddress");
            return (Criteria) this;
        }

        public Criteria andDeptAddressLessThan(String value) {
            addCriterion("dept_address <", value, "deptAddress");
            return (Criteria) this;
        }

        public Criteria andDeptAddressLessThanOrEqualTo(String value) {
            addCriterion("dept_address <=", value, "deptAddress");
            return (Criteria) this;
        }

        public Criteria andDeptAddressLike(String value) {
            addCriterion("dept_address like", value, "deptAddress");
            return (Criteria) this;
        }

        public Criteria andDeptAddressNotLike(String value) {
            addCriterion("dept_address not like", value, "deptAddress");
            return (Criteria) this;
        }

        public Criteria andDeptAddressIn(List<String> values) {
            addCriterion("dept_address in", values, "deptAddress");
            return (Criteria) this;
        }

        public Criteria andDeptAddressNotIn(List<String> values) {
            addCriterion("dept_address not in", values, "deptAddress");
            return (Criteria) this;
        }

        public Criteria andDeptAddressBetween(String value1, String value2) {
            addCriterion("dept_address between", value1, value2, "deptAddress");
            return (Criteria) this;
        }

        public Criteria andDeptAddressNotBetween(String value1, String value2) {
            addCriterion("dept_address not between", value1, value2, "deptAddress");
            return (Criteria) this;
        }

        public Criteria andDeptTypeIsNull() {
            addCriterion("dept_type is null");
            return (Criteria) this;
        }

        public Criteria andDeptTypeIsNotNull() {
            addCriterion("dept_type is not null");
            return (Criteria) this;
        }

        public Criteria andDeptTypeEqualTo(String value) {
            addCriterion("dept_type =", value, "deptType");
            return (Criteria) this;
        }

        public Criteria andDeptTypeNotEqualTo(String value) {
            addCriterion("dept_type <>", value, "deptType");
            return (Criteria) this;
        }

        public Criteria andDeptTypeGreaterThan(String value) {
            addCriterion("dept_type >", value, "deptType");
            return (Criteria) this;
        }

        public Criteria andDeptTypeGreaterThanOrEqualTo(String value) {
            addCriterion("dept_type >=", value, "deptType");
            return (Criteria) this;
        }

        public Criteria andDeptTypeLessThan(String value) {
            addCriterion("dept_type <", value, "deptType");
            return (Criteria) this;
        }

        public Criteria andDeptTypeLessThanOrEqualTo(String value) {
            addCriterion("dept_type <=", value, "deptType");
            return (Criteria) this;
        }

        public Criteria andDeptTypeLike(String value) {
            addCriterion("dept_type like", value, "deptType");
            return (Criteria) this;
        }

        public Criteria andDeptTypeNotLike(String value) {
            addCriterion("dept_type not like", value, "deptType");
            return (Criteria) this;
        }

        public Criteria andDeptTypeIn(List<String> values) {
            addCriterion("dept_type in", values, "deptType");
            return (Criteria) this;
        }

        public Criteria andDeptTypeNotIn(List<String> values) {
            addCriterion("dept_type not in", values, "deptType");
            return (Criteria) this;
        }

        public Criteria andDeptTypeBetween(String value1, String value2) {
            addCriterion("dept_type between", value1, value2, "deptType");
            return (Criteria) this;
        }

        public Criteria andDeptTypeNotBetween(String value1, String value2) {
            addCriterion("dept_type not between", value1, value2, "deptType");
            return (Criteria) this;
        }

        public Criteria andDeptPhoneIsNull() {
            addCriterion("dept_phone is null");
            return (Criteria) this;
        }

        public Criteria andDeptPhoneIsNotNull() {
            addCriterion("dept_phone is not null");
            return (Criteria) this;
        }

        public Criteria andDeptPhoneEqualTo(String value) {
            addCriterion("dept_phone =", value, "deptPhone");
            return (Criteria) this;
        }

        public Criteria andDeptPhoneNotEqualTo(String value) {
            addCriterion("dept_phone <>", value, "deptPhone");
            return (Criteria) this;
        }

        public Criteria andDeptPhoneGreaterThan(String value) {
            addCriterion("dept_phone >", value, "deptPhone");
            return (Criteria) this;
        }

        public Criteria andDeptPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("dept_phone >=", value, "deptPhone");
            return (Criteria) this;
        }

        public Criteria andDeptPhoneLessThan(String value) {
            addCriterion("dept_phone <", value, "deptPhone");
            return (Criteria) this;
        }

        public Criteria andDeptPhoneLessThanOrEqualTo(String value) {
            addCriterion("dept_phone <=", value, "deptPhone");
            return (Criteria) this;
        }

        public Criteria andDeptPhoneLike(String value) {
            addCriterion("dept_phone like", value, "deptPhone");
            return (Criteria) this;
        }

        public Criteria andDeptPhoneNotLike(String value) {
            addCriterion("dept_phone not like", value, "deptPhone");
            return (Criteria) this;
        }

        public Criteria andDeptPhoneIn(List<String> values) {
            addCriterion("dept_phone in", values, "deptPhone");
            return (Criteria) this;
        }

        public Criteria andDeptPhoneNotIn(List<String> values) {
            addCriterion("dept_phone not in", values, "deptPhone");
            return (Criteria) this;
        }

        public Criteria andDeptPhoneBetween(String value1, String value2) {
            addCriterion("dept_phone between", value1, value2, "deptPhone");
            return (Criteria) this;
        }

        public Criteria andDeptPhoneNotBetween(String value1, String value2) {
            addCriterion("dept_phone not between", value1, value2, "deptPhone");
            return (Criteria) this;
        }

        public Criteria andDeptQrcodeIsNull() {
            addCriterion("dept_qrcode is null");
            return (Criteria) this;
        }

        public Criteria andDeptQrcodeIsNotNull() {
            addCriterion("dept_qrcode is not null");
            return (Criteria) this;
        }

        public Criteria andDeptQrcodeEqualTo(String value) {
            addCriterion("dept_qrcode =", value, "deptQrcode");
            return (Criteria) this;
        }

        public Criteria andDeptQrcodeNotEqualTo(String value) {
            addCriterion("dept_qrcode <>", value, "deptQrcode");
            return (Criteria) this;
        }

        public Criteria andDeptQrcodeGreaterThan(String value) {
            addCriterion("dept_qrcode >", value, "deptQrcode");
            return (Criteria) this;
        }

        public Criteria andDeptQrcodeGreaterThanOrEqualTo(String value) {
            addCriterion("dept_qrcode >=", value, "deptQrcode");
            return (Criteria) this;
        }

        public Criteria andDeptQrcodeLessThan(String value) {
            addCriterion("dept_qrcode <", value, "deptQrcode");
            return (Criteria) this;
        }

        public Criteria andDeptQrcodeLessThanOrEqualTo(String value) {
            addCriterion("dept_qrcode <=", value, "deptQrcode");
            return (Criteria) this;
        }

        public Criteria andDeptQrcodeLike(String value) {
            addCriterion("dept_qrcode like", value, "deptQrcode");
            return (Criteria) this;
        }

        public Criteria andDeptQrcodeNotLike(String value) {
            addCriterion("dept_qrcode not like", value, "deptQrcode");
            return (Criteria) this;
        }

        public Criteria andDeptQrcodeIn(List<String> values) {
            addCriterion("dept_qrcode in", values, "deptQrcode");
            return (Criteria) this;
        }

        public Criteria andDeptQrcodeNotIn(List<String> values) {
            addCriterion("dept_qrcode not in", values, "deptQrcode");
            return (Criteria) this;
        }

        public Criteria andDeptQrcodeBetween(String value1, String value2) {
            addCriterion("dept_qrcode between", value1, value2, "deptQrcode");
            return (Criteria) this;
        }

        public Criteria andDeptQrcodeNotBetween(String value1, String value2) {
            addCriterion("dept_qrcode not between", value1, value2, "deptQrcode");
            return (Criteria) this;
        }

        public Criteria andDeptSceneIdIsNull() {
            addCriterion("dept_scene_id is null");
            return (Criteria) this;
        }

        public Criteria andDeptSceneIdIsNotNull() {
            addCriterion("dept_scene_id is not null");
            return (Criteria) this;
        }

        public Criteria andDeptSceneIdEqualTo(String value) {
            addCriterion("dept_scene_id =", value, "deptSceneId");
            return (Criteria) this;
        }

        public Criteria andDeptSceneIdNotEqualTo(String value) {
            addCriterion("dept_scene_id <>", value, "deptSceneId");
            return (Criteria) this;
        }

        public Criteria andDeptSceneIdGreaterThan(String value) {
            addCriterion("dept_scene_id >", value, "deptSceneId");
            return (Criteria) this;
        }

        public Criteria andDeptSceneIdGreaterThanOrEqualTo(String value) {
            addCriterion("dept_scene_id >=", value, "deptSceneId");
            return (Criteria) this;
        }

        public Criteria andDeptSceneIdLessThan(String value) {
            addCriterion("dept_scene_id <", value, "deptSceneId");
            return (Criteria) this;
        }

        public Criteria andDeptSceneIdLessThanOrEqualTo(String value) {
            addCriterion("dept_scene_id <=", value, "deptSceneId");
            return (Criteria) this;
        }

        public Criteria andDeptSceneIdLike(String value) {
            addCriterion("dept_scene_id like", value, "deptSceneId");
            return (Criteria) this;
        }

        public Criteria andDeptSceneIdNotLike(String value) {
            addCriterion("dept_scene_id not like", value, "deptSceneId");
            return (Criteria) this;
        }

        public Criteria andDeptSceneIdIn(List<String> values) {
            addCriterion("dept_scene_id in", values, "deptSceneId");
            return (Criteria) this;
        }

        public Criteria andDeptSceneIdNotIn(List<String> values) {
            addCriterion("dept_scene_id not in", values, "deptSceneId");
            return (Criteria) this;
        }

        public Criteria andDeptSceneIdBetween(String value1, String value2) {
            addCriterion("dept_scene_id between", value1, value2, "deptSceneId");
            return (Criteria) this;
        }

        public Criteria andDeptSceneIdNotBetween(String value1, String value2) {
            addCriterion("dept_scene_id not between", value1, value2, "deptSceneId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table gd_dept
     *
     * @mbggenerated do_not_delete_during_merge Sat Jan 09 21:57:21 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table gd_dept
     *
     * @mbggenerated Sat Jan 09 21:57:21 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}