package app.guangda.repository.model;

public class GdPtoper {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gd_ptoper.PKID
     *
     * @mbggenerated Sat Jan 09 21:57:21 CST 2016
     */
    private String pkid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gd_ptoper.ID
     *
     * @mbggenerated Sat Jan 09 21:57:21 CST 2016
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gd_ptoper.NAME
     *
     * @mbggenerated Sat Jan 09 21:57:21 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gd_ptoper.PASSWD
     *
     * @mbggenerated Sat Jan 09 21:57:21 CST 2016
     */
    private String passwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gd_ptoper.ISSUPER
     *
     * @mbggenerated Sat Jan 09 21:57:21 CST 2016
     */
    private String issuper;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gd_ptoper.DUTY
     *
     * @mbggenerated Sat Jan 09 21:57:21 CST 2016
     */
    private String duty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gd_ptoper.TYPE
     *
     * @mbggenerated Sat Jan 09 21:57:21 CST 2016
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gd_ptoper.SEX
     *
     * @mbggenerated Sat Jan 09 21:57:21 CST 2016
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gd_ptoper.EMAIL
     *
     * @mbggenerated Sat Jan 09 21:57:21 CST 2016
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gd_ptoper.MOBILEPHONE
     *
     * @mbggenerated Sat Jan 09 21:57:21 CST 2016
     */
    private String mobilephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gd_ptoper.PHONE
     *
     * @mbggenerated Sat Jan 09 21:57:21 CST 2016
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gd_ptoper.OTHERPHONE
     *
     * @mbggenerated Sat Jan 09 21:57:21 CST 2016
     */
    private String otherphone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gd_ptoper.ENABLED
     *
     * @mbggenerated Sat Jan 09 21:57:21 CST 2016
     */
    private String enabled;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gd_ptoper.ARCHIVED_FLAG
     *
     * @mbggenerated Sat Jan 09 21:57:21 CST 2016
     */
    private String archivedFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gd_ptoper.CREATED_BY
     *
     * @mbggenerated Sat Jan 09 21:57:21 CST 2016
     */
    private String createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gd_ptoper.CREATED_TIME
     *
     * @mbggenerated Sat Jan 09 21:57:21 CST 2016
     */
    private String createdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gd_ptoper.LAST_UPD_BY
     *
     * @mbggenerated Sat Jan 09 21:57:21 CST 2016
     */
    private String lastUpdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gd_ptoper.LAST_UPD_TIME
     *
     * @mbggenerated Sat Jan 09 21:57:21 CST 2016
     */
    private String lastUpdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gd_ptoper.REMARK
     *
     * @mbggenerated Sat Jan 09 21:57:21 CST 2016
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gd_ptoper.REC_VERSION
     *
     * @mbggenerated Sat Jan 09 21:57:21 CST 2016
     */
    private Integer recVersion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gd_ptoper.ATTACHMENT
     *
     * @mbggenerated Sat Jan 09 21:57:21 CST 2016
     */
    private String attachment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gd_ptoper.ONLINE_SITUATION
     *
     * @mbggenerated Sat Jan 09 21:57:21 CST 2016
     */
    private String onlineSituation;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gd_ptoper.PKID
     *
     * @return the value of gd_ptoper.PKID
     *
     * @mbggenerated Sat Jan 09 21:57:21 CST 2016
     */
    public String getPkid() {
        return pkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gd_ptoper.PKID
     *
     * @param pkid the value for gd_ptoper.PKID
     *
     * @mbggenerated Sat Jan 09 21:57:21 CST 2016
     */
    public void setPkid(String pkid) {
        this.pkid = pkid == null ? null : pkid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gd_ptoper.ID
     *
     * @return the value of gd_ptoper.ID
     *
     * @mbggenerated Sat Jan 09 21:57:21 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gd_ptoper.ID
     *
     * @param id the value for gd_ptoper.ID
     *
     * @mbggenerated Sat Jan 09 21:57:21 CST 2016
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gd_ptoper.NAME
     *
     * @return the value of gd_ptoper.NAME
     *
     * @mbggenerated Sat Jan 09 21:57:21 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gd_ptoper.NAME
     *
     * @param name the value for gd_ptoper.NAME
     *
     * @mbggenerated Sat Jan 09 21:57:21 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gd_ptoper.PASSWD
     *
     * @return the value of gd_ptoper.PASSWD
     *
     * @mbggenerated Sat Jan 09 21:57:21 CST 2016
     */
    public String getPasswd() {
        return passwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gd_ptoper.PASSWD
     *
     * @param passwd the value for gd_ptoper.PASSWD
     *
     * @mbggenerated Sat Jan 09 21:57:21 CST 2016
     */
    public void setPasswd(String passwd) {
        this.passwd = passwd == null ? null : passwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gd_ptoper.ISSUPER
     *
     * @return the value of gd_ptoper.ISSUPER
     *
     * @mbggenerated Sat Jan 09 21:57:21 CST 2016
     */
    public String getIssuper() {
        return issuper;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gd_ptoper.ISSUPER
     *
     * @param issuper the value for gd_ptoper.ISSUPER
     *
     * @mbggenerated Sat Jan 09 21:57:21 CST 2016
     */
    public void setIssuper(String issuper) {
        this.issuper = issuper == null ? null : issuper.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gd_ptoper.DUTY
     *
     * @return the value of gd_ptoper.DUTY
     *
     * @mbggenerated Sat Jan 09 21:57:21 CST 2016
     */
    public String getDuty() {
        return duty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gd_ptoper.DUTY
     *
     * @param duty the value for gd_ptoper.DUTY
     *
     * @mbggenerated Sat Jan 09 21:57:21 CST 2016
     */
    public void setDuty(String duty) {
        this.duty = duty == null ? null : duty.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gd_ptoper.TYPE
     *
     * @return the value of gd_ptoper.TYPE
     *
     * @mbggenerated Sat Jan 09 21:57:21 CST 2016
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gd_ptoper.TYPE
     *
     * @param type the value for gd_ptoper.TYPE
     *
     * @mbggenerated Sat Jan 09 21:57:21 CST 2016
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gd_ptoper.SEX
     *
     * @return the value of gd_ptoper.SEX
     *
     * @mbggenerated Sat Jan 09 21:57:21 CST 2016
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gd_ptoper.SEX
     *
     * @param sex the value for gd_ptoper.SEX
     *
     * @mbggenerated Sat Jan 09 21:57:21 CST 2016
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gd_ptoper.EMAIL
     *
     * @return the value of gd_ptoper.EMAIL
     *
     * @mbggenerated Sat Jan 09 21:57:21 CST 2016
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gd_ptoper.EMAIL
     *
     * @param email the value for gd_ptoper.EMAIL
     *
     * @mbggenerated Sat Jan 09 21:57:21 CST 2016
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gd_ptoper.MOBILEPHONE
     *
     * @return the value of gd_ptoper.MOBILEPHONE
     *
     * @mbggenerated Sat Jan 09 21:57:21 CST 2016
     */
    public String getMobilephone() {
        return mobilephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gd_ptoper.MOBILEPHONE
     *
     * @param mobilephone the value for gd_ptoper.MOBILEPHONE
     *
     * @mbggenerated Sat Jan 09 21:57:21 CST 2016
     */
    public void setMobilephone(String mobilephone) {
        this.mobilephone = mobilephone == null ? null : mobilephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gd_ptoper.PHONE
     *
     * @return the value of gd_ptoper.PHONE
     *
     * @mbggenerated Sat Jan 09 21:57:21 CST 2016
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gd_ptoper.PHONE
     *
     * @param phone the value for gd_ptoper.PHONE
     *
     * @mbggenerated Sat Jan 09 21:57:21 CST 2016
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gd_ptoper.OTHERPHONE
     *
     * @return the value of gd_ptoper.OTHERPHONE
     *
     * @mbggenerated Sat Jan 09 21:57:21 CST 2016
     */
    public String getOtherphone() {
        return otherphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gd_ptoper.OTHERPHONE
     *
     * @param otherphone the value for gd_ptoper.OTHERPHONE
     *
     * @mbggenerated Sat Jan 09 21:57:21 CST 2016
     */
    public void setOtherphone(String otherphone) {
        this.otherphone = otherphone == null ? null : otherphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gd_ptoper.ENABLED
     *
     * @return the value of gd_ptoper.ENABLED
     *
     * @mbggenerated Sat Jan 09 21:57:21 CST 2016
     */
    public String getEnabled() {
        return enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gd_ptoper.ENABLED
     *
     * @param enabled the value for gd_ptoper.ENABLED
     *
     * @mbggenerated Sat Jan 09 21:57:21 CST 2016
     */
    public void setEnabled(String enabled) {
        this.enabled = enabled == null ? null : enabled.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gd_ptoper.ARCHIVED_FLAG
     *
     * @return the value of gd_ptoper.ARCHIVED_FLAG
     *
     * @mbggenerated Sat Jan 09 21:57:21 CST 2016
     */
    public String getArchivedFlag() {
        return archivedFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gd_ptoper.ARCHIVED_FLAG
     *
     * @param archivedFlag the value for gd_ptoper.ARCHIVED_FLAG
     *
     * @mbggenerated Sat Jan 09 21:57:21 CST 2016
     */
    public void setArchivedFlag(String archivedFlag) {
        this.archivedFlag = archivedFlag == null ? null : archivedFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gd_ptoper.CREATED_BY
     *
     * @return the value of gd_ptoper.CREATED_BY
     *
     * @mbggenerated Sat Jan 09 21:57:21 CST 2016
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gd_ptoper.CREATED_BY
     *
     * @param createdBy the value for gd_ptoper.CREATED_BY
     *
     * @mbggenerated Sat Jan 09 21:57:21 CST 2016
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy == null ? null : createdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gd_ptoper.CREATED_TIME
     *
     * @return the value of gd_ptoper.CREATED_TIME
     *
     * @mbggenerated Sat Jan 09 21:57:21 CST 2016
     */
    public String getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gd_ptoper.CREATED_TIME
     *
     * @param createdTime the value for gd_ptoper.CREATED_TIME
     *
     * @mbggenerated Sat Jan 09 21:57:21 CST 2016
     */
    public void setCreatedTime(String createdTime) {
        this.createdTime = createdTime == null ? null : createdTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gd_ptoper.LAST_UPD_BY
     *
     * @return the value of gd_ptoper.LAST_UPD_BY
     *
     * @mbggenerated Sat Jan 09 21:57:21 CST 2016
     */
    public String getLastUpdBy() {
        return lastUpdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gd_ptoper.LAST_UPD_BY
     *
     * @param lastUpdBy the value for gd_ptoper.LAST_UPD_BY
     *
     * @mbggenerated Sat Jan 09 21:57:21 CST 2016
     */
    public void setLastUpdBy(String lastUpdBy) {
        this.lastUpdBy = lastUpdBy == null ? null : lastUpdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gd_ptoper.LAST_UPD_TIME
     *
     * @return the value of gd_ptoper.LAST_UPD_TIME
     *
     * @mbggenerated Sat Jan 09 21:57:21 CST 2016
     */
    public String getLastUpdTime() {
        return lastUpdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gd_ptoper.LAST_UPD_TIME
     *
     * @param lastUpdTime the value for gd_ptoper.LAST_UPD_TIME
     *
     * @mbggenerated Sat Jan 09 21:57:21 CST 2016
     */
    public void setLastUpdTime(String lastUpdTime) {
        this.lastUpdTime = lastUpdTime == null ? null : lastUpdTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gd_ptoper.REMARK
     *
     * @return the value of gd_ptoper.REMARK
     *
     * @mbggenerated Sat Jan 09 21:57:21 CST 2016
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gd_ptoper.REMARK
     *
     * @param remark the value for gd_ptoper.REMARK
     *
     * @mbggenerated Sat Jan 09 21:57:21 CST 2016
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gd_ptoper.REC_VERSION
     *
     * @return the value of gd_ptoper.REC_VERSION
     *
     * @mbggenerated Sat Jan 09 21:57:21 CST 2016
     */
    public Integer getRecVersion() {
        return recVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gd_ptoper.REC_VERSION
     *
     * @param recVersion the value for gd_ptoper.REC_VERSION
     *
     * @mbggenerated Sat Jan 09 21:57:21 CST 2016
     */
    public void setRecVersion(Integer recVersion) {
        this.recVersion = recVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gd_ptoper.ATTACHMENT
     *
     * @return the value of gd_ptoper.ATTACHMENT
     *
     * @mbggenerated Sat Jan 09 21:57:21 CST 2016
     */
    public String getAttachment() {
        return attachment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gd_ptoper.ATTACHMENT
     *
     * @param attachment the value for gd_ptoper.ATTACHMENT
     *
     * @mbggenerated Sat Jan 09 21:57:21 CST 2016
     */
    public void setAttachment(String attachment) {
        this.attachment = attachment == null ? null : attachment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gd_ptoper.ONLINE_SITUATION
     *
     * @return the value of gd_ptoper.ONLINE_SITUATION
     *
     * @mbggenerated Sat Jan 09 21:57:21 CST 2016
     */
    public String getOnlineSituation() {
        return onlineSituation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gd_ptoper.ONLINE_SITUATION
     *
     * @param onlineSituation the value for gd_ptoper.ONLINE_SITUATION
     *
     * @mbggenerated Sat Jan 09 21:57:21 CST 2016
     */
    public void setOnlineSituation(String onlineSituation) {
        this.onlineSituation = onlineSituation == null ? null : onlineSituation.trim();
    }
}