package app.guangda.repository.model;

public class GdSubscribeLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gd_subscribe_log.pkid
     *
     * @mbggenerated Sat Jan 09 21:57:21 CST 2016
     */
    private String pkid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gd_subscribe_log.dept_code
     *
     * @mbggenerated Sat Jan 09 21:57:21 CST 2016
     */
    private String deptCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gd_subscribe_log.openid
     *
     * @mbggenerated Sat Jan 09 21:57:21 CST 2016
     */
    private String openid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gd_subscribe_log.subscribe_type
     *
     * @mbggenerated Sat Jan 09 21:57:21 CST 2016
     */
    private String subscribeType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gd_subscribe_log.create_time
     *
     * @mbggenerated Sat Jan 09 21:57:21 CST 2016
     */
    private String createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gd_subscribe_log.pkid
     *
     * @return the value of gd_subscribe_log.pkid
     *
     * @mbggenerated Sat Jan 09 21:57:21 CST 2016
     */
    public String getPkid() {
        return pkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gd_subscribe_log.pkid
     *
     * @param pkid the value for gd_subscribe_log.pkid
     *
     * @mbggenerated Sat Jan 09 21:57:21 CST 2016
     */
    public void setPkid(String pkid) {
        this.pkid = pkid == null ? null : pkid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gd_subscribe_log.dept_code
     *
     * @return the value of gd_subscribe_log.dept_code
     *
     * @mbggenerated Sat Jan 09 21:57:21 CST 2016
     */
    public String getDeptCode() {
        return deptCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gd_subscribe_log.dept_code
     *
     * @param deptCode the value for gd_subscribe_log.dept_code
     *
     * @mbggenerated Sat Jan 09 21:57:21 CST 2016
     */
    public void setDeptCode(String deptCode) {
        this.deptCode = deptCode == null ? null : deptCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gd_subscribe_log.openid
     *
     * @return the value of gd_subscribe_log.openid
     *
     * @mbggenerated Sat Jan 09 21:57:21 CST 2016
     */
    public String getOpenid() {
        return openid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gd_subscribe_log.openid
     *
     * @param openid the value for gd_subscribe_log.openid
     *
     * @mbggenerated Sat Jan 09 21:57:21 CST 2016
     */
    public void setOpenid(String openid) {
        this.openid = openid == null ? null : openid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gd_subscribe_log.subscribe_type
     *
     * @return the value of gd_subscribe_log.subscribe_type
     *
     * @mbggenerated Sat Jan 09 21:57:21 CST 2016
     */
    public String getSubscribeType() {
        return subscribeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gd_subscribe_log.subscribe_type
     *
     * @param subscribeType the value for gd_subscribe_log.subscribe_type
     *
     * @mbggenerated Sat Jan 09 21:57:21 CST 2016
     */
    public void setSubscribeType(String subscribeType) {
        this.subscribeType = subscribeType == null ? null : subscribeType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gd_subscribe_log.create_time
     *
     * @return the value of gd_subscribe_log.create_time
     *
     * @mbggenerated Sat Jan 09 21:57:21 CST 2016
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gd_subscribe_log.create_time
     *
     * @param createTime the value for gd_subscribe_log.create_time
     *
     * @mbggenerated Sat Jan 09 21:57:21 CST 2016
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }
}