package app.guangda.repository.model;

public class GdSubscribeUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gd_subscribe_user.pkid
     *
     * @mbggenerated Sat Jan 09 21:57:21 CST 2016
     */
    private String pkid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gd_subscribe_user.dept_code
     *
     * @mbggenerated Sat Jan 09 21:57:21 CST 2016
     */
    private String deptCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gd_subscribe_user.openid
     *
     * @mbggenerated Sat Jan 09 21:57:21 CST 2016
     */
    private String openid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gd_subscribe_user.name
     *
     * @mbggenerated Sat Jan 09 21:57:21 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gd_subscribe_user.phone
     *
     * @mbggenerated Sat Jan 09 21:57:21 CST 2016
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gd_subscribe_user.address
     *
     * @mbggenerated Sat Jan 09 21:57:21 CST 2016
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gd_subscribe_user.create_time
     *
     * @mbggenerated Sat Jan 09 21:57:21 CST 2016
     */
    private String createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gd_subscribe_user.subscribe_flag
     *
     * @mbggenerated Sat Jan 09 21:57:21 CST 2016
     */
    private String subscribeFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gd_subscribe_user.recversion
     *
     * @mbggenerated Sat Jan 09 21:57:21 CST 2016
     */
    private Integer recversion;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gd_subscribe_user.pkid
     *
     * @return the value of gd_subscribe_user.pkid
     *
     * @mbggenerated Sat Jan 09 21:57:21 CST 2016
     */
    public String getPkid() {
        return pkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gd_subscribe_user.pkid
     *
     * @param pkid the value for gd_subscribe_user.pkid
     *
     * @mbggenerated Sat Jan 09 21:57:21 CST 2016
     */
    public void setPkid(String pkid) {
        this.pkid = pkid == null ? null : pkid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gd_subscribe_user.dept_code
     *
     * @return the value of gd_subscribe_user.dept_code
     *
     * @mbggenerated Sat Jan 09 21:57:21 CST 2016
     */
    public String getDeptCode() {
        return deptCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gd_subscribe_user.dept_code
     *
     * @param deptCode the value for gd_subscribe_user.dept_code
     *
     * @mbggenerated Sat Jan 09 21:57:21 CST 2016
     */
    public void setDeptCode(String deptCode) {
        this.deptCode = deptCode == null ? null : deptCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gd_subscribe_user.openid
     *
     * @return the value of gd_subscribe_user.openid
     *
     * @mbggenerated Sat Jan 09 21:57:21 CST 2016
     */
    public String getOpenid() {
        return openid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gd_subscribe_user.openid
     *
     * @param openid the value for gd_subscribe_user.openid
     *
     * @mbggenerated Sat Jan 09 21:57:21 CST 2016
     */
    public void setOpenid(String openid) {
        this.openid = openid == null ? null : openid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gd_subscribe_user.name
     *
     * @return the value of gd_subscribe_user.name
     *
     * @mbggenerated Sat Jan 09 21:57:21 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gd_subscribe_user.name
     *
     * @param name the value for gd_subscribe_user.name
     *
     * @mbggenerated Sat Jan 09 21:57:21 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gd_subscribe_user.phone
     *
     * @return the value of gd_subscribe_user.phone
     *
     * @mbggenerated Sat Jan 09 21:57:21 CST 2016
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gd_subscribe_user.phone
     *
     * @param phone the value for gd_subscribe_user.phone
     *
     * @mbggenerated Sat Jan 09 21:57:21 CST 2016
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gd_subscribe_user.address
     *
     * @return the value of gd_subscribe_user.address
     *
     * @mbggenerated Sat Jan 09 21:57:21 CST 2016
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gd_subscribe_user.address
     *
     * @param address the value for gd_subscribe_user.address
     *
     * @mbggenerated Sat Jan 09 21:57:21 CST 2016
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gd_subscribe_user.create_time
     *
     * @return the value of gd_subscribe_user.create_time
     *
     * @mbggenerated Sat Jan 09 21:57:21 CST 2016
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gd_subscribe_user.create_time
     *
     * @param createTime the value for gd_subscribe_user.create_time
     *
     * @mbggenerated Sat Jan 09 21:57:21 CST 2016
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gd_subscribe_user.subscribe_flag
     *
     * @return the value of gd_subscribe_user.subscribe_flag
     *
     * @mbggenerated Sat Jan 09 21:57:21 CST 2016
     */
    public String getSubscribeFlag() {
        return subscribeFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gd_subscribe_user.subscribe_flag
     *
     * @param subscribeFlag the value for gd_subscribe_user.subscribe_flag
     *
     * @mbggenerated Sat Jan 09 21:57:21 CST 2016
     */
    public void setSubscribeFlag(String subscribeFlag) {
        this.subscribeFlag = subscribeFlag == null ? null : subscribeFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gd_subscribe_user.recversion
     *
     * @return the value of gd_subscribe_user.recversion
     *
     * @mbggenerated Sat Jan 09 21:57:21 CST 2016
     */
    public Integer getRecversion() {
        return recversion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gd_subscribe_user.recversion
     *
     * @param recversion the value for gd_subscribe_user.recversion
     *
     * @mbggenerated Sat Jan 09 21:57:21 CST 2016
     */
    public void setRecversion(Integer recversion) {
        this.recversion = recversion;
    }
}